### ISSUE TITLE
Is this repo SpoutcraftPlugin 2.0?

### ISSUE THREAD

**Issue by Dockter** [Limeth/CustomItemLibrary#5]
Hello,

As the last person who maintained Spoutcraft I look at this project as a re implementation of it.

Trust me when I tell you, stop now.....

https://github.com/Spoutcraft/SpoutcraftPlugin

**Comment by Limeth** [comment]
Hello,
thank you for your concerns. Compared to the SpoutcraftPlugin, if I understand correctly, this library does not require any client-side mods. I am aware that this library may introduce a performance decrease when custom blocks are over-used. I don't see this as an unsolvable problem.
I would highly appreciate any feedback from experienced developers of Spoutcraft.

**Comment by Limeth** [comment]
So I've explored through the Spoutcraft codebase a little more. I can safely say that I do not plan to recreate the SpoutcraftPlugin. The goal of this library is to provide common features plugins could use, while staying maintainable. The features I want in this library are almost all implemented already, there are just a couple of issues I'd like to get resolved and then release it as 1.0. I want to keep this as minimalist as possible, while also being tightly integrated with the Sponge API, so I don't end up reinventing the wheel.
